export {
  ALLOWED_ORIGINS,
  getAllowedOrigin,
  corsHeaders,
  rateLimitMap,
  RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX,
  isRateLimited,
  EMAIL_RE,
  isValidEmail,
  UUID_RE,
  isValidUuid,
  sanitizeSearch,
  json,
  jsonError,
  CODIGO_CAPACIDAD_INSUFICIENTE,
  removeAccents,
} from '../../compat/api/lib/utils.js'
